### ISSUE TITLE
NOT WORKING Ubuntu 18 64 bit

### ISSUE THREAD

**Issue by astrayal** [steadfasterX/SALT#28]
hello, 
wanted to let you know this doesn't work on ubuntu 18 
ERROR:
Fatal error missing requirement
python-zstandard (python3)

seems in ubuntu dist. the package has been renamed to Zstd
see info here
https://launchpad.net/ubuntu/bionic/amd64/zstd

not sure where to go from here any idea?
perhaps edit a config file to use zstd instead of python-zstandard???
any help is appreciated

**Comment by steadfasterX** [comment]
zstd is not zstandard.
Read the OP of the salt support thread and the release notes in the same thread . The OP has for all major distributions described what to do .
