### ISSUE TITLE
Salt not detecting my device (LG D685)

### ISSUE THREAD

**Issue by TheBatman** [steadfasterX/SALT#34]
Imma attach the salt log.
[salt.log](https://github.com/steadfasterX/SALT/files/4699764/salt.log)

I'm on Manjaro btw, thanks in advance!

**Comment by steadfasterX** [comment]
Thx for the log. Try this:

1. Boot device in download mode 
2. Connect it to the pc 
3. Boot / reboot your pc with the device connected 

If that does not work try other cables and USB 2 ports are more reliable sometimes

**Comment by TheBatman** [comment]
Howdy! sorry for the delay :+1: 
No luck :( still same result, here i attach a screenshot
![Captura de pantalla de 2020-05-30 20-13-50](https://user-images.githubusercontent.com/13712357/83342225-688a6480-a2b2-11ea-9326-a90065f131b9.png)

**Comment by steadfasterX** [comment]
You tried:

- different cables?
- usb 2 and usb 3 ports?
- connecting device before booting?

One more thing: sometimes adb is possible only when you switch to MTP (aka file transfer) or PTP (aka photo transfer) modes!

**Comment by TheBatman** [comment]
Hello! 
here's the output:
```
~ >>> lsusb                                                                    
Bus 003 Device 003: ID 04f2:b40e Chicony Electronics Co., Ltd HP Truevision HD camera
Bus 003 Device 002: ID 0438:7900 Advanced Micro Devices, Inc. Root Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0bda:b001 Realtek Semiconductor Corp. 
Bus 001 Device 004: ID 1004:61f1 LG Electronics, Inc. Optimus Android Phone [LG Software mode]
Bus 001 Device 002: ID 0438:7900 Advanced Micro Devices, Inc. Root Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 002 Device 003: ID 03f0:0f0c HP, Inc Wireless Keyboard and Optical Mouse receiver
Bus 002 Device 002: ID 046d:c246 Logitech, Inc. Gaming Mouse G300
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

```
different cables? =Had to use a different USB cable to boot my device in download mode but still Salt is not detecting it 
usb 2 and usb 3 ports? = Yes
connecting device before booting? R= Yup

**Comment by steadfasterX** [comment]
> Bus 001 Device 004: ID 1004:61f1 LG Electronics, Inc. Optimus Android Phone [LG Software mode]

ok then the only thing left is waiting >= 5 min after booting into download mode, then connect it to the PC.

**Comment by TheBatman** [comment]
Sad times, it didn't work :(
![Captura de pantalla de 2020-06-04 11-00-50](https://user-images.githubusercontent.com/13712357/83780532-e6ec5b00-a652-11ea-83dd-933aba8a8c0c.png)
waited 6 mins to plug it

**Comment by steadfasterX** [comment]
well that's bad. what happens when you do this?

```
cd ~/programs/lglafng/
sudo python lglaf.py --debug 
```

**Comment by TheBatman** [comment]
This is the output:
```
Traceback (most recent call last):
  File "lglaf.py", line 569, in <module>
    main()
  File "lglaf.py", line 532, in main
    comm = autodetect_device(args.cr)
  File "lglaf.py", line 453, in autodetect_device
    return USBCommunication(cr)
  File "lglaf.py", line 299, in __init__
    raise RuntimeError("USB device not found")
RuntimeError: USB device not found
~/programs/lglafng >>>           
```    
![Captura de pantalla de 2020-06-04 18-06-47](https://user-images.githubusercontent.com/13712357/83818970-4156dd00-a68e-11ea-9213-f63df8ca7d1a.png)

**Comment by steadfasterX** [comment]
well never had an issue like that before.. you could try booting mAid from an USB stick to see if that works out. SALT and LGlaf is included there already and dozens of mods made to make sure these connections are working as they should. no guarantees ofc but that's the only thing left (or the download mode is just buggy on the device)

https://maid.binbash.rocks -> click _nightly builds_ button at the top right. I recommend mAid_v2020-04-21_23-43_x86_64_forgetful.iso atm as there are some icon bugs in the latest releases

**Comment by steadfasterX** [comment]
no user response. closed
